[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "uvicorn src.lanabot.main:app --host 0.0.0.0 --port $PORT"

[deploy.healthcheck]
path = "/health"
port = 8000
initialDelaySeconds = 10
periodSeconds = 10

[env]
PYTHON_VERSION = "3.12"
